# Generated by Django 2.1.2 on 2018-11-20 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='brand_name',
            field=models.CharField(default='None', max_length=60),
        ),
        migrations.AddField(
            model_name='feed',
            name='categories',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feed',
            name='currency',
            field=models.CharField(default='USD', max_length=5),
        ),
        migrations.AddField(
            model_name='feed',
            name='pagination',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feed',
            name='platform',
            field=models.CharField(default='woocommerce', max_length=35),
        ),
        migrations.AddField(
            model_name='feed',
            name='prod_condition',
            field=models.CharField(default='new', max_length=10),
        ),
        migrations.AlterField(
            model_name='feed',
            name='website',
            field=models.CharField(default='https://www.google.com', max_length=300, unique=True),
        ),
    ]
