# Generated by Django 2.1.2 on 2018-11-20 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Feed', '0002_auto_20181120_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='website',
            field=models.CharField(default='https://www.google.com', max_length=300),
        ),
    ]
